### ISSUE TITLE
The library does not work with Rpi5

### ISSUE THREAD

**Issue by rajeevkr945** [pimoroni/rpi_ws281x-python#109] opened 2024-03-27 05:50 UTC
### interfacing issues with Rpi 5

the issues are explained here: https://forums.raspberrypi.com/viewtopic.php?t=365166
PLEASE MENTION IF THERE ARE ANY WORKAROUND

**Comment by Gadgetoid** [comment] 2024-03-28 09:21
Dupe of #106

**Closed as completed by Gadgetoid** 2024-03-28 09:21 UTC
